version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    expose:
      - "8000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    networks:
      - app-network

  cloudflared:
    image: "cloudflare/cloudflared:latest"
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: always

networks:
  app-network: