# Use the official Nginx image from the Docker Hub
FROM nginx:stable-alpine-slim

# Copy the custom Nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port that Nginx will serve on
EXPOSE 80