# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set environment variables to ensure that Python output is sent straight to the terminal
# and prevent Python from buffering outputs
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY ./static ./static
COPY ./templates ./templates
COPY .env .
COPY ./app.py .

# Expose the port that the Flask app runs on
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]